# Build settings

port: 4000
markdown: kramdown
permalink: /:title
plugins:   [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title: "Jeffrey Kang"
description: ""
author: "Jeffrey Kang"
baseurl: ""
url: "https://jeffreylckang.github.io"

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: home
