#-------------------------------
# General Site Settings

menu:
- {name: 'About', url: '/'}
- {name: 'Projects', url: 'projects'}
- {name: 'Resume', url: 'resume'}
- {name: 'Contact', url: 'contact'}

#-------------------------------
# Projects Section

projects:
- {name: 'Using ML to Identify Value Bets',   url: '/valuebets'}
- {name: 'Understanding Grocery Shopping Payments',   url: '/grocery'}

#-------------------------------

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Jeffrey Kang portfolio'
  rel-author: 'https://jeffreykang.github.io'
  rel-publisher: 'https://jeffreykang.github.io'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: ''

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''
